import "@/styles/globals.css";

import Login from "@/components/Login";
import Sidebar from "@/components/Sidebar";
import { getCurrentUser } from "@/pages/api/auth/session";
import ClientProvider from "@/components/ClientProvider";

export const metadata = {
  title: "ChatGPT Clone",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getCurrentUser();
  return (
    <html>
      <body>
        {!user ? (
          <Login />
        ) : (
          <div className="flex">
            <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
              <Sidebar
                user={{
                  name: user.name,
                  image: user.image,
                  email: user.email,
                }}
              />
            </div>
            <ClientProvider />
            <div className="bg-[#343541] flex-1">{children}</div>
          </div>
        )}
      </body>
    </html>
  );
}
